### ISSUE TITLE
If dependent apps are not running, unhelpful error is returned

### ISSUE THREAD

**Issue by vinayvinay** [alphagov/publishing-api#24]
Actual:
```bash
// url-arbiter, content-store are not running
$ make run
$ curl http://localhost:3000/content/new-vat-rates -X PUT -H 'Content-type: application/json' -d '<content-item-json>'
> {"Offset":1}
```

Expected error message:
```bash
> FATAL: Couldn't connect to URL Arbiter at http://url-arbiter.dev.gov.uk.
```

**Comment by jamiecobbett** [comment]
This is currently happening on preview.

**Comment by jamiecobbett** [comment]
I don't think it's because the dependencies aren't running - you've sent invalid JSON. The response body: `{"Offset":1}` is the serialized error object because we're supplying it as the third argument (the body) here: https://github.com/alphagov/publishing-api/blob/master/content_store_controller.go#L44

You would have received the right HTTP status, but I think we should work on the response bodies.

I haven't figured out what's wrong on preview yet.

**Comment by vinayvinay** [comment]
Hi Jamie: I confirmed again that this happens with one of the services being down as well. The same request returns the offset error, which it not the case when all dependent services are up:
```
$ curl http://localhost:3093/content/new-vat-rates -X PUT -H 'Content-type: application/json' -d '{"content_id": "a5d86183-7252-4426-aad2-3f732f7f2581", "title": "VAT Rates", "publishing_app":"publisher", "format": "guide", "update_type": "minor", "rendering_app":"frontend", "routes": [{"path":"/new-vat-rates", "type": "exact"}]}'
=> {"Offset":1}
```

**Comment by alext** [comment]
I think this will be because we're doing things like 
```go
renderer.JSON(w, http.StatusInternalServerError, err)
```
in our error handling code, which is just asking renderer to serialise an error object to JSON.  This will probably just pull the fields out of the underlying struct, and they won't make much sense out of context (as we're seeing).

I'd suggest that we should either not return JSON in this case, and just return `text/plain` with the error message (`err.Error()`), or construct some meaningful JSON that includes this full error message.

**Comment by jamiecobbett** [comment]
I made a start on returning saner errors, but got a bit bogged down trying to do it in Go. I've opened this PR in url-arbiter which I plan to apply to publishing-api: https://github.com/alphagov/url-arbiter/pull/19
